language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.5
      env: SYMFONY_VERSION="2.2.x"
    - php: 5.5
      env: SYMFONY_VERSION="2.3.x"
    - php: 5.5
      env: SYMFONY_VERSION="2.4.x"
    - php: 5.5
      env: SYMFONY_VERSION="2.5.x"
    - php: 5.5
      env: SYMFONY_VERSION="2.6.x@dev"
    - php: 5.5
      env: SYMFONY_VERSION="2.7.x@dev"

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi'
  - composer install
